### PR TITLE
Automatically throttle the click events for the button component

### PR DESCRIPTION
**Pull request by mariadoesmath**

### CODE REVIEW

**Review by emilng — APPROVED** [review]
Looks good! Do you think we should move this test case over? https://github.com/Hireology/app/blob/wip/app/assets/javascripts/react/shared/components/Button/__tests__/Button-test.jsx#L93

**Comment by mariadoesmath** [comment]
Good call

- [ ] Add throttle clicks test

**Comment by mariadoesmath** [comment]
Good thing you added that to because I accidentally didn't call the throttle function so it wasn't even working 😬

**Comment by emilng** [comment]
> Good thing you added that to because I accidentally didn't call the throttle function so it wasn't even working 😬

I think I had the same thing happen to me when I worked on it and I also missed that in the PR 😬

**Pull request merged**
